config/routes.rb
Blackboard::Application.routes.draw do

  get "/about", to: "static_pages#about", as: "about"

  get "users/:nickname", to: 'users#show', as: "user"
  delete "users/:nickname", to: 'users#destroy'

  get '/auth/:provider',          to: 'sessions#new', as: "new_session"
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/sessions',             to: "sessions#destroy", as: "session"

  resources :groups
  resources :projects
  resources :user_projects, only: [:create, :update, :destroy]
  resources :goal_completions, only: [:create]

  root "blackboard#show"

end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :projects, ->{ order(id: :asc) }

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate!, except: [:show, :index]
  before_action :authenticate_admin!, except: [:show, :index]

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @group.destroy
    redirect_to group_url, notice: 'Group was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def group_params
    params.require(:group).permit(:name, :description)
  end
end

app/views/groups/_form.html.erb
<%= semantic_nested_form_for(@group) do |f| %>
  <%= f.inputs %>
  <%= f.actions %>
<% end %>

app/views/groups/_group.html.erb
<li>
  <h2><%= link_to group.name, group_path(group) %></h2>
  <%= pluralize group.projects.count, 'project' %>
</li>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>All project groups</h1>

<p class="lead">
  This is a list of all the project groups currently on the site.
</p>
<p>
  Blackboard projects are organised by the skills, languages or tools needed to complete them. Each group will describe exactly what is required to get started.
</p>

<ul>
  <%= render @groups %>
</ul>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<h1><%= @group.name %> projects</h1>

<%= markdown @group.description %>

<h2>Projects:</h2>
<ul>
  <%= render @group.projects %>
</ul>