config/routes.rb
Blackboard::Application.routes.draw do

  get "/about", to: "static_pages#about", as: "about"

  get "users/:nickname", to: 'users#show', as: "user"
  delete "users/:nickname", to: 'users#destroy'

  get '/auth/:provider',          to: 'sessions#new', as: "new_session"
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/sessions',             to: "sessions#destroy", as: "session"

  resources :groups
  resources :projects
  resources :user_projects, only: [:create, :update, :destroy]
  resources :goal_completions, only: [:create]

  root "blackboard#show"

end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :group
  has_many :goals, ->{ order(id: :asc) }
  accepts_nested_attributes_for :goals, reject_if: :all_blank, allow_destroy: true

  has_many :user_projects
  has_many :users, through: :user_projects

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate!, except: [:show, :index]
  before_action :authenticate_admin!, except: [:show, :index]

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show
    @project_presenter = ProjectPresenter.new(@project, current_user)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def project_params
    params.require(:project).permit(:group_id, :name, :summary, :description, goals_attributes: [:id, :title, :description, :tips, :project_id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def status_partial_for_user_project(user_project)
    if current_user.nil?
      "projects/status/needs_login"
    elsif user_project.nil?
      "projects/status/ready"
    elsif user_project.complete?
      "projects/status/finished"
    else
      "projects/status/in_progress"
    end
  end

end

app/views/projects/status/_finished.html.erb
You've completed this project.

<%= render partial: 'user_projects/github_repo_form', locals: {user_project: @project_presenter.current_user_project } %>

app/views/projects/status/_in_progress.html.erb
You're working on this project.

<%= button_to(
      "I'm not working on this any more",
      user_project_path(@project_presenter.current_user_project),
      method: :delete,
      class: "btn"
    ) %>

Your project is <%= @project_presenter.current_user_project.percentage_completion %>% complete.

<%= render partial: 'user_projects/github_repo_form', locals: {user_project: @project_presenter.current_user_project } %>

app/views/projects/status/_needs_login.html.erb
Want to let people know you're working in this project?
<%= link_to("Log in via GitHub", new_session_path(provider: "github")) %>

app/views/projects/status/_ready.html.erb
<%= button_to "I want to start work on this", user_projects_path(project_id: @project.id), class: "btn" %>