config/routes.rb
Blackboard::Application.routes.draw do

  get "/about", to: "static_pages#about", as: "about"

  get "users/:nickname", to: 'users#show', as: "user"
  delete "users/:nickname", to: 'users#destroy'

  get '/auth/:provider',          to: 'sessions#new', as: "new_session"
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/sessions',             to: "sessions#destroy", as: "session"

  resources :groups
  resources :projects
  resources :user_projects, only: [:create, :update, :destroy]
  resources :goal_completions, only: [:create]

  root "blackboard#show"

end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :group
  has_many :goals, ->{ order(id: :asc) }
  accepts_nested_attributes_for :goals, reject_if: :all_blank, allow_destroy: true

  has_many :user_projects
  has_many :users, through: :user_projects

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate!, except: [:show, :index]
  before_action :authenticate_admin!, except: [:show, :index]

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show
    @project_presenter = ProjectPresenter.new(@project, current_user)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def project_params
    params.require(:project).permit(:group_id, :name, :summary, :description, goals_attributes: [:id, :title, :description, :tips, :project_id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def status_partial_for_user_project(user_project)
    if current_user.nil?
      "projects/status/needs_login"
    elsif user_project.nil?
      "projects/status/ready"
    elsif user_project.complete?
      "projects/status/finished"
    else
      "projects/status/in_progress"
    end
  end

end

app/views/projects/_form.html.erb
<%= semantic_nested_form_for(@project) do |f| %>
  <%= f.inputs name: "Project" do %>
    <%= f.input :group, include_blank: false, input_html: {class: "input-medium"} %>
    <%= f.input :name %>
    <%= f.input :summary %>
    <%= f.input :description, input_html: {class: "input-xxlarge"} %>
  <% end %>
  <%= f.fields_for :goals do |goal_form| %>
    <%= render "goals/fields", goal_form: goal_form %>
  <% end %>
  <p><%= f.link_to_add "Add a goal", :goals %></p>
  <%= f.actions %>
<% end %>

app/views/projects/_project.html.erb
<li><%= link_to project.name, project_path(project) %></li>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>All projects</h1>

<p class="lead">
  This is a list of all the projects currently on the site.
</p>

<p>
  Blackboard projects are organised by the skills, languages or tools needed to complete them - you may find it easier to look for a new project on
  <%= link_to "the projects by type page.", groups_path %>
</p>

<ul>
  <%= render @projects %>
</ul>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<p class="lead"><%= @project.summary %></p>
<p><%= markdown @project.description %></p>

<div>
  <%= render partial: status_partial_for_user_project(@project_presenter.current_user_project) %>
</div>

<h2>What exactly will my program need to do?</h2>
<div class="accordion" id="accordion1">
  <%= render @project.goals %>
</div>

<div class="row-fluid">
  <ul id="working-users" class="span6">
    <%= render @project_presenter.worked_on_user_projects %>
  </ul>
  <ul id="finished-users" class="span6">
    <%= render @project_presenter.completed_user_projects %>
  </ul>
</div>