config/routes.rb
Blackboard::Application.routes.draw do

  get "/about", to: "static_pages#about", as: "about"

  get "users/:nickname", to: 'users#show', as: "user"
  delete "users/:nickname", to: 'users#destroy'

  get '/auth/:provider',          to: 'sessions#new', as: "new_session"
  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/sessions',             to: "sessions#destroy", as: "session"

  resources :groups
  resources :projects
  resources :user_projects, only: [:create, :update, :destroy]
  resources :goal_completions, only: [:create]

  root "blackboard#show"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blackboard" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="container">

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <div class="ribbon-wrapper-green"><div class="ribbon-green">BETA</div></div>
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                    <%= link_to "Blackboard", root_path, class: "brand" %>
                    <div class="nav-collapse collapse">
                      <ul class="nav">
                        <% nav_links.each_pair do |text, path| %>
                          <li class="<%= 'active' if current_page?(path) %>"><%= link_to(text, path) %></li>
                        <% end %>
                      </ul>
                      <ul class="nav user-nav pull-right">
                        <% if user_signed_in? %>
                          <li id="current-user">
                            <%= link_to user_path(current_user) do %>
                              <%= image_tag current_user.image_url, class: "img", width: 35, height: 35 %>
                              &nbsp;
                              <%= current_user.display_name %>
                            <% end %>
                          </li>
                          <li><%= link_to "Log out", session_path, method: :delete %></li>
                        <% else %>
                          <li><%= link_to "Log in via GitHub", new_session_path(provider: "github") %></li>
                        <% end %>
                      </ul>
                    </div>
                </div>
            </div>
        </div>

        <%= bootstrap_flash %>
        <%= yield %>

        <hr/>

    </div>

  </body>
</html>